[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  branch = "mm14334a"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"
